# Generated by Django 5.0.10 on 2025-01-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=250)),
                ("year", models.IntegerField()),
                ("duration", models.IntegerField(blank=True, null=True)),
                ("synopsis", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "data.movie",
            },
        ),
    ]
