# Generated by Django 5.0.10 on 2025-01-09 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('birthdate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('year', models.IntegerField()),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('poster_uri', models.CharField(blank=True, max_length=15, null=True)),
                ('actors', models.ManyToManyField(db_table='play', related_name='played_movies', to='movieapp.person')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='directed_movies', to='movieapp.person')),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
