# Generated by Django 5.0.10 on 2025-01-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movieapp", "0002_movie_color_movie_poster_uri_alter_movie_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                ("birthdate", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "data.person",
            },
        ),
    ]
